### ISSUE TITLE
The H5 Writer callback doesn't take into account offset induced by `limit_bounds`

### ISSUE THREAD

**Issue by AjeyPaiK** [NKI-AI/ahcore#16]
In ahcore, we use limit_bounds on slides which do not have any rois specified for it. This is especially helpful when we have whole slide images (WSI) which have a lot of redundant (unwanted background) tiles.

If we use limit_bounds, an offset is required to properly demarcate the region where we can find the tissue specimen on the WSI. 

However, the `H5FileImageWriter` doesn't account for this currently and it breaks while writing h5 files.

**Comment by jonasteuwen** [comment]
See https://github.com/NKI-AI/dlup/pull/201 for a streamlined way to address this
