### ISSUE TITLE
If use_roi is set to False, the pretransform will still try to use an roi because of the initialization from dlup

### ISSUE THREAD

**Issue by moerlemans** [NKI-AI/ahcore#21]
**Describe the bug**
In the pretransforms there is an if statement to check for ROI's, but the statement doesn't work as ROIs are always in the sample, but they can be None. The error happens [here](https://github.com/NKI-AI/ahcore/blob/58a200c6679e6882f44c8212e6af6beee120588a/ahcore/transforms/pre_transforms.py#L233). Due to the way `sample['annotation_data']` is created, the if statement will always pass (as the key "roi" is always present) and then in line 235 it will throw an error as a None object isn't subscriptable

**To Reproduce**
Run any model in training mode with use_roi=False

**Expected behavior**
The if-statement should actually check if the ROI is not None

**Environment**
dlup version:
How installed:
Python version:
Operating System:

**Additional context**

**Comment by jonasteuwen** [comment]
Can you post a stacktrace?

**Comment by moerlemans** [comment]
[here](https://github.com/NKI-AI/ahcore/blob/58a200c6679e6882f44c8212e6af6beee120588a/ahcore/transforms/pre_transforms.py#L233) there will always be an error thrown if there are no rois because the key "roi" is always made (probably also a typeddict). So the if statement is redundant and should be changed to something like `if "roi" in sample["annotation_data"] and sample["annotation_data"]["roi"] is not None:` 

If you agree I can just replace the if-statement with the above and PR
