### ISSUE TITLE
Enable Macenko Normalisation for P1000 images

### ISSUE THREAD

**Issue by sinberlin2** [NKI-AI/ahcore#23]
**Describe the bug**
The P1000 images have an offset that needs to be taken into consideration. Otherwise the normalisation will occur with stain vectors that are largely based on white background.

**To Reproduce**
Run macenko with any P1000 images and visualise output.

**Expected behavior**
The slide_image needs to be offset to compute the stain vectors across the wsi area.
**Environment**
dlup version:
How installed:
Python version:
Operating System:

**Additional context**

**Comment by AjeyPaiK** [comment]
Hi @sinberlin2 , thanks for raising the issue.

I'm trying to understand it. Do you mean to say that stain vectors are hard to calculate over the WSI for P1000 images since there is a lot of background and very little tissue region in these images?

**Comment by sinberlin2** [comment]
Hello Ajey, I tried to add more details in the PR. You can also check the lines I have added in the code for further clarification. It is just 3 lines basically

**Comment by AjeyPaiK** [comment]
Awesome, I'll check it and also test it. Thanks Shannon! :)
