### ISSUE TITLE
CCITTFAX4 compression is not supported by tiffile in upstream dlup.

### ISSUE THREAD

**Issue by AjeyPaiK** [NKI-AI/ahcore#48]
**Describe the bug**
Writing tiff files using the `tiff_callback` breaks when we use CCITTFAX4 compression. I get the following error:

![image](https://github.com/NKI-AI/ahcore/assets/26798611/793600c4-ee16-4c3b-a716-a4f003ad8e9d)

**To Reproduce**
Write any tiff image using the tiff callback.

**Expected behavior**
N/A

**Environment**
dlup version: 0.3.35
How installed: Installed using pip as an editable package
Python version: 3.9.5
Operating System: linux

**Additional context**
N/A

**Comment by moerlemans** [comment]
This is fixed by changing https://github.com/NKI-AI/ahcore/blob/960f25aa533d0f3b2386b27e00e025d938c3ef8f/ahcore/callbacks/tiff_callback.py#L203 to ZSTD
